=== AgileNinjas/Airline-Company-Ticket-Reservation/XMLSchema/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="schedule">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="flight" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== AgileNinjas/Airline-Company-Ticket-Reservation/AirlineReservationService/xmls/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../XMLSchema/schedule.xsd">
    <flight>
        <id>1</id>
    </flight>
    <flight>
        <id>2</id>
    </flight>
    <flight>
        <id>3</id>
    </flight>
    <flight>
        <id>4</id>
    </flight>
    <flight>
        <id>5</id>
    </flight>
</schedule>
